# User
EMAIL_MAX_LENGTH = 255
PASSWORD_MAX_LENGTH = 255
NAME_MAX_LENGTH = 100


RECIPE_TITLE_MAX_LENGTH = 255
RECIPE_DESCRIPTION_MAX_LENGTH = 1000
RECIPE_COOK_TIME_MAX_LENGTH = 50
RECIPE_DIFFICULTY_MAX_LENGTH = 50
RECIPE_WHY_FITS_MAX_LENGTH = 500
DIET_MAX_LENGTH = 50
IMAGE_URL_MAX_LENGTH = 500